export const USER_SIGN_UP = 'USER_SIGN_UP'
export const USER_SIGN_UP_REQUEST = 'USER_SIGN_UP_REQUEST'
export const USER_ERROR = 'USER_ERROR'

export const USER_LOGIN = 'USER_LOGIN'
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'

export const CONFIRM_ENTRANCE_SIGNUP = 'CONFIRM_ENTRANCE_SIGNUP'
export const CONFIRM_ENTRANCE_SIGNUP_REQUEST = 'CONFIRM_ENTRANCE_SIGNUP_REQUEST'

export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST'
export const FETCH_USER = 'FETCH_USER'

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT = 'LOGOUT'
